// Ideas for how each charism might be lived out — at home, in the parish,
// and in the wider community. These are original FamilyWise suggestions
// written to prompt reflection, not assignments and not a claim that anyone
// has a given charism; edit freely.

export const CHARISM_EXAMPLES: Record<string, string[]> = {
  administration: [
    "Coordinate a parish event, retreat, or meal train from start to finish",
    "Serve on a parish council or a finance or building committee",
    "Organize volunteer schedules for a ministry",
    "Bring order to the family calendar, budget, or household routines",
    "Help a school or charity plan its work and resources",
  ],
  leadership: [
    "Lead a small group, youth group, or ministry team",
    "Guide a parish project or outreach from vision to completion",
    "Help your family agree on a shared mission and rhythms of prayer",
    "Mentor emerging leaders and give them room to use their gifts",
    "Step forward to guide a group through a hard decision",
  ],
  craftsmanship: [
    "Repair, build, or improve things for the parish, a school, or a neighbor",
    "Make or maintain liturgical items, banners, or furnishings",
    "Join a service project that builds or restores homes",
    "Teach your children a hands-on skill, offering the work to God",
    "Quietly care for the church grounds and buildings",
  ],
  creativity: [
    "Serve in the parish music, choir, or liturgical art ministry",
    "Write, design, or film something that shares the faith",
    "Create family prayer traditions, Advent crafts, or storytelling",
    "Help decorate the church for the liturgical seasons",
    "Bring drama, poetry, or photography into youth or children's ministry",
  ],
  teaching: [
    "Teach children's faith formation or a youth class",
    "Lead a Bible study or parish faith-sharing group",
    "Explain the faith to your children in everyday moments",
    "Tutor or coach students who are struggling",
    "Prepare talks or lessons for parents, couples, or newcomers to the faith",
  ],
  knowledge: [
    "Research and prepare material for a Bible study or faith-formation team",
    "Help others find reliable answers about Church teaching",
    "Build a family reading plan around the faith",
    "Support the parish with research, writing, or archives",
    "Study a topic deeply and share what you learn with your community",
  ],
  wisdom: [
    "Offer a listening ear and counsel to friends facing big decisions",
    "Mentor engaged or newly married couples",
    "Serve on a parish pastoral or discernment group",
    "Help your family weigh important choices in prayer",
    "Be a steady voice for young adults in a season of change",
  ],
  discernment: [
    "Walk with a friend through a vocation or life decision",
    "Serve on a retreat team that helps others listen for the Spirit",
    "Help a parish group test whether a new idea is truly good for the community",
    "Help your family sort out the influences shaping your home, from screens to friendships",
    "Pray with others about their choices as a trusted, prayerful listener",
  ],
  prophecy: [
    "Speak up with charity for the unborn, the poor, and the vulnerable",
    "Gently name where your community is being called to grow in faithfulness",
    "Share a word of challenge or conviction in a faith-sharing group",
    "Stand for the truth at home in ways your children can understand",
    "Write or speak about faith and justice in your community",
  ],
  faith: [
    "Pray with trust alongside families facing a hard season",
    "Join a parish prayer team and expect God to act",
    "Encourage others who feel a situation is impossible",
    "Step out in trust on a parish or mission project that seems too big",
    "Share how God has been faithful in your own life",
  ],
  intercession: [
    "Join a parish prayer chain or take a regular adoration hour",
    "Pray the Rosary for family and friends by name",
    "Keep a prayer list for the intentions you are asked to carry",
    "Lead or join intercessory prayer at parish gatherings",
    "Offer to pray right then with someone who shares a need",
  ],
  healing: [
    "Visit the sick, the homebound, or the grieving",
    "Serve in a hospital, hospice, or caregiving ministry",
    "Join a parish bereavement or support team",
    "Pray with and listen to family members who are hurting",
    "Walk alongside people recovering from loss, illness, or addiction",
  ],
  piety: [
    "Serve the liturgy as a sacristan, lector, or Eucharistic minister",
    "Lead family devotions such as the Rosary, grace at meals, and Sunday Mass",
    "Help with Eucharistic adoration or other parish devotions",
    "Join a liturgy or sacrament-preparation team",
    "Mark the liturgical year at home with prayer and traditions",
  ],
  service: [
    "Set up, clean up, and quietly handle the details behind the scenes",
    "Join a meal ministry or help families in need with practical tasks",
    "Notice and take care of needs at home without being asked",
    "Drive, run errands, or offer childcare for others",
    "Support those in ministry by lightening their load",
  ],
  hospitality: [
    "Welcome people as a greeter or usher, or at a newcomers' coffee hour",
    "Host a family dinner or small group in your home",
    "Make a point of including new parishioners and families",
    "Help organize parish fellowship events",
    "Reach out to people who are lonely or new in the neighborhood",
  ],
  encouragement: [
    "Write notes, call, or message people who are struggling",
    "Mentor someone who is new to the faith or to ministry",
    "Cheer on your family members' efforts, big and small",
    "Join a small group that supports people through hard times",
    "Be a steady voice of hope among friends and coworkers",
  ],
  evangelization: [
    "Invite a friend or neighbor to Mass or a parish event",
    "Join an outreach team or a mission trip",
    "Share your faith story when the moment is natural",
    "Help welcome seekers through an introductory faith course",
    "Witness to the faith through the way your family lives and serves",
  ],
  giving: [
    "Give generously to the parish and to those in need",
    "Sponsor a family, a child, or a mission project",
    "Offer your time and skills as part of your giving, not only money",
    "Teach your children the joy of giving",
    "Quietly meet a specific need you notice among friends and neighbors",
  ],
};
